# Generated by Django 3.2.4 on 2021-06-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
