# Generated by Django 3.2.4 on 2021-06-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0002_auto_20210611_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price_ht',
        ),
    ]
