# Generated by Django 3.2.4 on 2021-06-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0005_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
